import MeasureToMeasure.Foundations.Sphere
import Mathlib.Analysis.Convex.Integral
import Mathlib.Analysis.Normed.Lp.MeasurableSpace

/-!
# Leaf L11: disjoint geodesic hulls force non-colinear barycenters (review finding F2)

The induction in Proposition 3.1 (disentanglement) silently uses the implication

  `conv_g supp μ ∩ conv_g supp ν = ∅`  ⟹  `ℰ_μ[x]` and `ℰ_ν[x]` are not colinear,

for measures supported in the open orthant `Q₁^{d-1}`. The paper states this without proof; the
adversarial review (`RESEARCH.md`, finding F2) flagged it as the one genuine rigor gap. This file
discharges the geometric core.

## The mathematics

Within an open hemisphere, spherical geodesics are the radial projections of Euclidean chords, so the
geodesic-convex hull of a set `s` coincides with `cone(s) ∩ 𝕊^{d-1}` — the convex cone generated by
`s`, intersected with the sphere. We take this characterization as the definition (`geodesicHull`),
which is faithful in the orthant (an open hemisphere).

The barycenter `ℰ_μ[x] = ∫ x dμ` is a nonnegative average of points of `supp μ`, hence lies in
`cone(supp μ)`; normalizing, its direction lies in `geodesicHull (supp μ)`. If two barycenters were
colinear (the same ray — both lie in the positive orthant, so "colinear" means a *positive* multiple,
i.e. `SameRay`), they would share a normalized direction `u`, and `u` would lie in *both* geodesic
hulls, contradicting disjointness.

## Scope (honest labeling)

We prove the core for the **finitely supported (empirical) barycenter** `∑ wₚ • p` with `wₚ ≥ 0` — a
manifest conical combination. This is exactly the regime of Theorem 1.1 (Dirac targets) and the
restricted Theorem 1.2 (empirical targets). For a general probability measure the only extra
ingredient is the standard fact "the barycenter lies in the closed convex hull of the support"; that
single measure-theoretic step is the documented residual (it does not reintroduce the optimal-transport
axioms). Everything in this file is kernel-checked.
-/

namespace MeasureToMeasure.Leaves

open scoped RealInnerProductSpace
open MeasureTheory

variable {d : ℕ}

/-- `x` is a nonnegative (conical) combination of the points of `s`. Membership in the convex cone
generated by `s`. -/
def inConicalSpan (s : Finset (Eucl d)) (x : Eucl d) : Prop :=
  ∃ t : Eucl d → ℝ, (∀ p ∈ s, 0 ≤ t p) ∧ x = ∑ p ∈ s, t p • p

/-- The geodesic-convex hull of `s`, modeled within a hemisphere as `cone(s) ∩ 𝕊^{d-1}`: the unit
vectors that are nonnegative combinations of `s`. Faithful to `conv_g` when `s` lies in an open
hemisphere (e.g. the orthant `Q₁^{d-1}`), since spherical geodesics are radial projections of chords. -/
def geodesicHull (s : Finset (Eucl d)) : Set (Eucl d) :=
  {x | ‖x‖ = 1 ∧ inConicalSpan s x}

/-- The conical span is closed under nonnegative scaling. -/
theorem inConicalSpan.smul {s : Finset (Eucl d)} {x : Eucl d} (h : inConicalSpan s x)
    {a : ℝ} (ha : 0 ≤ a) : inConicalSpan s (a • x) := by
  obtain ⟨t, ht, hx⟩ := h
  refine ⟨fun p => a * t p, fun p hp => mul_nonneg ha (ht p hp), ?_⟩
  rw [hx, Finset.smul_sum]
  simp_rw [smul_smul]

/-- The normalization `‖x‖⁻¹ • x` of a nonzero conical point lies on the sphere and in the geodesic
hull. -/
theorem mem_geodesicHull_normalize {s : Finset (Eucl d)} {x : Eucl d} (h : inConicalSpan s x)
    (hx : x ≠ 0) : (‖x‖⁻¹ • x) ∈ geodesicHull s := by
  have hnx : ‖x‖ ≠ 0 := norm_ne_zero_iff.mpr hx
  refine ⟨?_, h.smul (by positivity)⟩
  rw [norm_smul, norm_inv, norm_norm, inv_mul_cancel₀ hnx]

/-- The empirical barycenter `∑ wₚ • p` with nonnegative weights is a conical combination of `s`. -/
theorem barycenter_mem_conicalSpan {s : Finset (Eucl d)} {w : Eucl d → ℝ}
    (hw : ∀ p ∈ s, 0 ≤ w p) : inConicalSpan s (∑ p ∈ s, w p • p) :=
  ⟨w, hw, rfl⟩

/-- **Core of finding F2.** If two nonzero conical points `b`, `c` (the unnormalized barycenters) are
colinear — `SameRay ℝ b c`, i.e. positive multiples, which is what "colinear" means for vectors in the
positive orthant — then their common normalized direction lies in *both* geodesic hulls. -/
theorem geodesicHull_inter_nonempty_of_sameRay {s₁ s₂ : Finset (Eucl d)} {b c : Eucl d}
    (hb : inConicalSpan s₁ b) (hc : inConicalSpan s₂ c) (hb0 : b ≠ 0) (hc0 : c ≠ 0)
    (hsr : SameRay ℝ b c) : (geodesicHull s₁ ∩ geodesicHull s₂).Nonempty := by
  obtain ⟨r₁, r₂, hr₁, hr₂, hrel⟩ := hsr.exists_pos hb0 hc0
  -- `b = k • c` with `k = r₁⁻¹ r₂ > 0`
  set k : ℝ := r₁⁻¹ * r₂ with hkdef
  have hk : 0 < k := by positivity
  have hbk : b = k • c := by
    rw [hkdef, mul_smul, ← hrel, smul_smul, inv_mul_cancel₀ (ne_of_gt hr₁), one_smul]
  -- the normalized vectors coincide
  have key : ‖b‖⁻¹ • b = ‖c‖⁻¹ • c := by
    have hnc : ‖c‖ ≠ 0 := norm_ne_zero_iff.mpr hc0
    rw [hbk, norm_smul, Real.norm_eq_abs, abs_of_pos hk, smul_smul]
    congr 1
    field_simp
  refine ⟨‖b‖⁻¹ • b, ?_⟩
  rw [Set.mem_inter_iff]
  exact ⟨mem_geodesicHull_normalize hb hb0, key ▸ mem_geodesicHull_normalize hc hc0⟩

/-- **Finding F2, discharged.** Empirical measures (with nonnegative weights) in the orthant whose
geodesic hulls are disjoint have non-colinear barycenters. This is the step Proposition 3.1's
induction asserts without proof. -/
theorem barycenter_noncolinear_of_disjoint_hull {s₁ s₂ : Finset (Eucl d)} {w₁ w₂ : Eucl d → ℝ}
    (hw₁ : ∀ p ∈ s₁, 0 ≤ w₁ p) (hw₂ : ∀ p ∈ s₂, 0 ≤ w₂ p)
    (hb0 : (∑ p ∈ s₁, w₁ p • p) ≠ 0) (hc0 : (∑ p ∈ s₂, w₂ p • p) ≠ 0)
    (hdisj : Disjoint (geodesicHull s₁) (geodesicHull s₂)) :
    ¬ SameRay ℝ (∑ p ∈ s₁, w₁ p • p) (∑ p ∈ s₂, w₂ p • p) := by
  intro hsr
  obtain ⟨u, hu⟩ := geodesicHull_inter_nonempty_of_sameRay
    (barycenter_mem_conicalSpan hw₁) (barycenter_mem_conicalSpan hw₂) hb0 hc0 hsr
  rw [Set.mem_inter_iff] at hu
  exact Set.disjoint_left.mp hdisj hu.1 hu.2

/-!
## General measures (closing the F2 residual)

The finite case above is elementary. For a general probability measure the only extra ingredient is
the standard fact that the barycenter `∫ x dμ` lies in any closed convex set carrying full mass —
Mathlib's `Convex.integral_mem`. With it the same `SameRay` contradiction goes through for arbitrary
probability measures whose supports sit inside disjoint closed convex *cones*, with no new axioms.
-/

/-- The barycenter `ℰ_μ[x] = ∫ x dμ`, as a Bochner integral. -/
noncomputable def barycenter (μ : Measure (Eucl d)) : Eucl d := ∫ x, x ∂μ

/-- The barycenter of a probability measure lies in any closed convex set carrying full mass
(`μ Sᶜ = 0`). This is the standard measure-theoretic fact the general case of finding F2 needs; it
rests only on Mathlib's `Convex.integral_mem`, not on the optimal-transport axioms. -/
theorem barycenter_mem_of_supportedIn {μ : Measure (Eucl d)} [IsProbabilityMeasure μ]
    (hint : Integrable (fun x : Eucl d => x) μ) {s : Set (Eucl d)}
    (hconv : Convex ℝ s) (hclosed : IsClosed s) (hsupp : μ sᶜ = 0) :
    barycenter μ ∈ s := by
  have hae : ∀ᵐ x ∂μ, x ∈ s := by
    rw [ae_iff]; exact hsupp
  rw [barycenter]
  exact hconv.integral_mem hclosed hae hint

/-- **Finding F2, general case.** Two probability measures whose supports lie in disjoint closed
convex cones `s₁`, `s₂` (disjoint on the sphere) have non-colinear barycenters. Generalizes
`barycenter_noncolinear_of_disjoint_hull` from empirical to arbitrary probability measures; kernel-
clean, via `barycenter_mem_of_supportedIn`. -/
theorem barycenter_noncolinear_of_disjoint_hull_general
    {μ ν : Measure (Eucl d)} [IsProbabilityMeasure μ] [IsProbabilityMeasure ν]
    (hμi : Integrable (fun x : Eucl d => x) μ) (hνi : Integrable (fun x : Eucl d => x) ν)
    {s₁ s₂ : Set (Eucl d)}
    (hc₁ : Convex ℝ s₁) (hcl₁ : IsClosed s₁) (hcone₁ : ∀ x ∈ s₁, ∀ a : ℝ, 0 ≤ a → a • x ∈ s₁)
    (hc₂ : Convex ℝ s₂) (hcl₂ : IsClosed s₂) (hcone₂ : ∀ x ∈ s₂, ∀ a : ℝ, 0 ≤ a → a • x ∈ s₂)
    (hμs : μ s₁ᶜ = 0) (hνs : ν s₂ᶜ = 0)
    (hb0 : barycenter μ ≠ 0) (hc0 : barycenter ν ≠ 0)
    (hdisj : ∀ u : Eucl d, ‖u‖ = 1 → u ∈ s₁ → u ∉ s₂) :
    ¬ SameRay ℝ (barycenter μ) (barycenter ν) := by
  intro hsr
  set b := barycenter μ with hbdef
  set c := barycenter ν with hcdef
  obtain ⟨r₁, r₂, hr₁, hr₂, hrel⟩ := hsr.exists_pos hb0 hc0
  have hbs₁ : b ∈ s₁ := barycenter_mem_of_supportedIn hμi hc₁ hcl₁ hμs
  have hcs₂ : c ∈ s₂ := barycenter_mem_of_supportedIn hνi hc₂ hcl₂ hνs
  set k : ℝ := r₁⁻¹ * r₂ with hkdef
  have hk : 0 < k := by positivity
  have hbk : b = k • c := by
    rw [hkdef, mul_smul, ← hrel, smul_smul, inv_mul_cancel₀ (ne_of_gt hr₁), one_smul]
  have key : ‖b‖⁻¹ • b = ‖c‖⁻¹ • c := by
    have hnc : ‖c‖ ≠ 0 := norm_ne_zero_iff.mpr hc0
    rw [hbk, norm_smul, Real.norm_eq_abs, abs_of_pos hk, smul_smul]
    congr 1
    field_simp
  set u := ‖b‖⁻¹ • b with hu
  have hunorm : ‖u‖ = 1 := by
    rw [hu, norm_smul, norm_inv, norm_norm, inv_mul_cancel₀ (norm_ne_zero_iff.mpr hb0)]
  have hus₁ : u ∈ s₁ := by rw [hu]; exact hcone₁ b hbs₁ _ (by positivity)
  have hus₂ : u ∈ s₂ := by rw [key]; exact hcone₂ c hcs₂ _ (by positivity)
  exact hdisj u hunorm hus₁ hus₂

end MeasureToMeasure.Leaves
