import Mathlib.Topology.MetricSpace.Lipschitz
import MeasureToMeasure.Foundations.Sphere

/-!
# Reusable pieces for the gated cutoff Block (Lemma B.2, slice 2)

The gated characteristic of Appendix B.2 is generated by the vector field
`V_θ(x) = χ(‖x‖) · (⟪z,x⟫ - cos R)₊ · P_x^⊥ ω`, a scalar gate times the tangential projector
`P_x^⊥ ω = ω - ⟪x,ω⟫ x`. The projector is *quadratic* in `x`, so it is not globally Lipschitz;
the smooth cutoff `χ` supported near the sphere tames it. To assemble a genuine `Block` (which
requires a *globally* Lipschitz, *bounded* field) we need two reusable facts, proved here with no
reference to the specific field:

* `lipschitzWith_smul` — a **bounded**-Lipschitz product rule: if `f` and `V` are each Lipschitz
  *and* bounded, then `x ↦ f x • V x` is Lipschitz. (The plain `LipschitzWith.smul` needs one
  factor globally bounded; here both bounds enter the constant.)
* `normCutoff` — an explicit `1`-Lipschitz cutoff `χ(x) = max 0 (min 1 (2 - ‖x‖))`, equal to `1`
  on the unit ball and `0` outside the ball of radius `2`, with range `[0,1]`.

Slice 2b stacks the cutoff-tamed projector's global Lipschitz bound (a "Lipschitz on a ball +
vanishes outside → global" gluing argument) and the concrete `Block` on top of these.
-/

namespace MeasureToMeasure

open Set

variable {d : ℕ}

/-- **Bounded-Lipschitz product rule.** If `f : Eucl d → ℝ` is `Kf`-Lipschitz and bounded by `Bf`,
and `V : Eucl d → Eucl d` is `KV`-Lipschitz and bounded by `BV`, then the scalar-times-vector product
`x ↦ f x • V x` is `(Bf * KV + Kf * BV)`-Lipschitz. This is the tool that turns the two bounded,
locally-Lipschitz factors of the gated field into one globally Lipschitz field. -/
theorem lipschitzWith_smul {f : Eucl d → ℝ} {V : Eucl d → Eucl d}
    {Kf KV Bf BV : NNReal} (hf : LipschitzWith Kf f) (hV : LipschitzWith KV V)
    (hfb : ∀ x, ‖f x‖ ≤ Bf) (hVb : ∀ x, ‖V x‖ ≤ BV) :
    LipschitzWith (Bf * KV + Kf * BV) (fun x => f x • V x) := by
  apply LipschitzWith.of_dist_le_mul
  intro x y
  -- split `f x • V x - f y • V y = f x • (V x - V y) + (f x - f y) • V y`
  have hsplit : f x • V x - f y • V y = f x • (V x - V y) + (f x - f y) • V y := by
    rw [smul_sub, sub_smul]; abel
  rw [dist_eq_norm, hsplit]
  refine le_trans (norm_add_le _ _) ?_
  have h1 : ‖f x • (V x - V y)‖ ≤ (Bf : ℝ) * (KV * dist x y) := by
    rw [norm_smul]
    apply mul_le_mul (hfb x) _ (norm_nonneg _) (by positivity)
    rw [← dist_eq_norm]
    exact hV.dist_le_mul x y
  have h2 : ‖(f x - f y) • V y‖ ≤ (Kf : ℝ) * dist x y * BV := by
    rw [norm_smul]
    apply mul_le_mul _ (hVb y) (norm_nonneg _) (by positivity)
    rw [Real.norm_eq_abs, ← Real.dist_eq]
    exact hf.dist_le_mul x y
  push_cast
  calc ‖f x • (V x - V y)‖ + ‖(f x - f y) • V y‖
      ≤ (Bf : ℝ) * (KV * dist x y) + (Kf : ℝ) * dist x y * BV := add_le_add h1 h2
    _ = ((Bf : ℝ) * KV + (Kf : ℝ) * BV) * dist x y := by ring

/-- The explicit **norm cutoff** `χ(x) = max 0 (min 1 (2 - ‖x‖))`: it equals `1` on the closed unit
ball, `0` outside the open ball of radius `2`, takes values in `[0,1]`, and is `1`-Lipschitz. Used to
localize the (quadratic, hence non-Lipschitz) tangential projector near the sphere. -/
noncomputable def normCutoff (x : Eucl d) : ℝ := max 0 (min 1 (2 - ‖x‖))

theorem normCutoff_nonneg (x : Eucl d) : 0 ≤ normCutoff x := le_max_left _ _

theorem normCutoff_le_one (x : Eucl d) : normCutoff x ≤ 1 := by
  unfold normCutoff; exact max_le zero_le_one (le_trans (min_le_left _ _) le_rfl)

theorem abs_normCutoff_le_one (x : Eucl d) : |normCutoff x| ≤ 1 := by
  rw [abs_of_nonneg (normCutoff_nonneg x)]; exact normCutoff_le_one x

theorem normCutoff_eq_one {x : Eucl d} (hx : ‖x‖ ≤ 1) : normCutoff x = 1 := by
  unfold normCutoff
  have h1 : (1 : ℝ) ≤ 2 - ‖x‖ := by linarith
  rw [min_eq_left h1, max_eq_right zero_le_one]

theorem normCutoff_eq_zero {x : Eucl d} (hx : 2 ≤ ‖x‖) : normCutoff x = 0 := by
  unfold normCutoff
  have h1 : 2 - ‖x‖ ≤ 0 := by linarith
  rw [min_eq_right (le_trans h1 zero_le_one), max_eq_left h1]

theorem normCutoff_lipschitz : LipschitzWith 1 (normCutoff (d := d)) := by
  have hsub : LipschitzWith 1 (fun x : Eucl d => 2 - ‖x‖) := by
    apply LipschitzWith.of_dist_le_mul
    intro x y
    have heq : (2 - ‖x‖) - (2 - ‖y‖) = ‖y‖ - ‖x‖ := by ring
    rw [Real.dist_eq, heq, abs_sub_comm]
    simpa [dist_eq_norm] using abs_norm_sub_norm_le x y
  have hmin : LipschitzWith 1 (fun x : Eucl d => min 1 (2 - ‖x‖)) :=
    hsub.const_min 1
  have hmax : LipschitzWith 1 (fun x : Eucl d => max 0 (min 1 (2 - ‖x‖))) :=
    hmin.const_max 0
  exact hmax

end MeasureToMeasure
