import Mathlib.Topology.MetricSpace.Lipschitz
import MeasureToMeasure.Foundations.Sphere
import MeasureToMeasure.Foundations.Projector
import MeasureToMeasure.Foundations.FlowMap

/-!
# The gated cutoff `Block` (Lemma B.2, slice 2)

The gated characteristic of Appendix B.2 is generated by the vector field
`V_θ(x) = χ(‖x‖) · (⟪z,x⟫ - cos R)₊ · P_x^⊥ ω`, a scalar gate times the tangential projector
`P_x^⊥ ω = ω - ⟪x,ω⟫ x`. The projector is *quadratic* in `x`, so it is not globally Lipschitz; the
cutoff `χ` supported near the sphere tames it. A genuine `Block` needs a *globally* Lipschitz,
*bounded* field, so this file builds the field and discharges all `Block` obligations.

**Reusable gluing infrastructure** (field-independent):
* `lipschitzWith_smul` — a **bounded**-Lipschitz product rule: if `f` and `V` are each Lipschitz *and*
  bounded, then `x ↦ f x • V x` is Lipschitz.
* `normCutoff` — the explicit `1`-Lipschitz cutoff `χ(x) = max 0 (min 1 (2 - ‖x‖))`, equal to `1` on
  the unit ball and `0` outside the ball of radius `2`, range `[0,1]`.
* `lipschitzWith_smul_of_vanishing` — the key gluing fact: a compactly-supported bounded-Lipschitz
  scalar times a vector field that is bounded and Lipschitz *only on the ball* is globally Lipschitz.
  This is what turns the locally-Lipschitz quadratic projector into a global field.

**The concrete field and `Block`**:
* `gatedField z ω cosR = gateFactor · tangentialProjector` where `gateFactor = normCutoff · reluGate`.
* `gatedField_lipschitz` (`32`), `gatedField_norm_le` (`15`), `gatedField_radial` (gate
  `c(x) = -gateFactor x·⟪x,ω⟫`), `abs_two_gatedGate_le` (`12`), assembled into `gatedBlock`.

The field is `gateFactor • (true projector)` *everywhere* — the cutoff only tames the Lipschitz
estimate, it does not alter the field's algebra — so the radial-tangency identity holds by a global
computation with no case split.
-/

namespace MeasureToMeasure

open Set
open scoped RealInnerProductSpace

variable {d : ℕ}

/-- **Bounded-Lipschitz product rule.** If `f : Eucl d → ℝ` is `Kf`-Lipschitz and bounded by `Bf`,
and `V : Eucl d → Eucl d` is `KV`-Lipschitz and bounded by `BV`, then the scalar-times-vector product
`x ↦ f x • V x` is `(Bf * KV + Kf * BV)`-Lipschitz. This is the tool that turns the two bounded,
locally-Lipschitz factors of the gated field into one globally Lipschitz field. -/
theorem lipschitzWith_smul {f : Eucl d → ℝ} {V : Eucl d → Eucl d}
    {Kf KV Bf BV : NNReal} (hf : LipschitzWith Kf f) (hV : LipschitzWith KV V)
    (hfb : ∀ x, ‖f x‖ ≤ Bf) (hVb : ∀ x, ‖V x‖ ≤ BV) :
    LipschitzWith (Bf * KV + Kf * BV) (fun x => f x • V x) := by
  apply LipschitzWith.of_dist_le_mul
  intro x y
  -- split `f x • V x - f y • V y = f x • (V x - V y) + (f x - f y) • V y`
  have hsplit : f x • V x - f y • V y = f x • (V x - V y) + (f x - f y) • V y := by
    rw [smul_sub, sub_smul]; abel
  rw [dist_eq_norm, hsplit]
  refine le_trans (norm_add_le _ _) ?_
  have h1 : ‖f x • (V x - V y)‖ ≤ (Bf : ℝ) * (KV * dist x y) := by
    rw [norm_smul]
    apply mul_le_mul (hfb x) _ (norm_nonneg _) (by positivity)
    rw [← dist_eq_norm]
    exact hV.dist_le_mul x y
  have h2 : ‖(f x - f y) • V y‖ ≤ (Kf : ℝ) * dist x y * BV := by
    rw [norm_smul]
    apply mul_le_mul _ (hVb y) (norm_nonneg _) (by positivity)
    rw [Real.norm_eq_abs, ← Real.dist_eq]
    exact hf.dist_le_mul x y
  push_cast
  calc ‖f x • (V x - V y)‖ + ‖(f x - f y) • V y‖
      ≤ (Bf : ℝ) * (KV * dist x y) + (Kf : ℝ) * dist x y * BV := add_le_add h1 h2
    _ = ((Bf : ℝ) * KV + (Kf : ℝ) * BV) * dist x y := by ring

/-- The explicit **norm cutoff** `χ(x) = max 0 (min 1 (2 - ‖x‖))`: it equals `1` on the closed unit
ball, `0` outside the open ball of radius `2`, takes values in `[0,1]`, and is `1`-Lipschitz. Used to
localize the (quadratic, hence non-Lipschitz) tangential projector near the sphere. -/
noncomputable def normCutoff (x : Eucl d) : ℝ := max 0 (min 1 (2 - ‖x‖))

theorem normCutoff_nonneg (x : Eucl d) : 0 ≤ normCutoff x := le_max_left _ _

theorem normCutoff_le_one (x : Eucl d) : normCutoff x ≤ 1 := by
  unfold normCutoff; exact max_le zero_le_one (le_trans (min_le_left _ _) le_rfl)

theorem abs_normCutoff_le_one (x : Eucl d) : |normCutoff x| ≤ 1 := by
  rw [abs_of_nonneg (normCutoff_nonneg x)]; exact normCutoff_le_one x

theorem normCutoff_eq_one {x : Eucl d} (hx : ‖x‖ ≤ 1) : normCutoff x = 1 := by
  unfold normCutoff
  have h1 : (1 : ℝ) ≤ 2 - ‖x‖ := by linarith
  rw [min_eq_left h1, max_eq_right zero_le_one]

theorem normCutoff_eq_zero {x : Eucl d} (hx : 2 ≤ ‖x‖) : normCutoff x = 0 := by
  unfold normCutoff
  have h1 : 2 - ‖x‖ ≤ 0 := by linarith
  rw [min_eq_right (le_trans h1 zero_le_one), max_eq_left h1]

/-- **Compactly-supported scalar times a locally-bounded-Lipschitz vector field is globally
Lipschitz.** If `s` is `Ks`-Lipschitz, bounded by `Bs`, and *vanishes outside the ball of radius `R`*,
and `V` is `Kv`-Lipschitz and `Bv`-bounded *on that ball*, then `x ↦ s x • V x` is
`(Bs·Kv + Ks·Bv)`-Lipschitz. This is the gluing fact that tames the quadratic projector `ω - ⟪x,ω⟫x`
(only locally Lipschitz) once the cutoff `s` localizes it near the sphere: only the projector's
behaviour on the ball enters, and when the far point has `s = 0` the difference collapses to one term
whose coefficient is controlled by `|s x| = |s x - s y| ≤ Ks‖x-y‖`. -/
theorem lipschitzWith_smul_of_vanishing {F : Type*} [NormedAddCommGroup F] [NormedSpace ℝ F]
    {s : Eucl d → ℝ} {V : Eucl d → F}
    {Ks Bs Kv Bv R : NNReal} (hsL : LipschitzWith Ks s) (hsB : ∀ x, |s x| ≤ Bs)
    (hvanish : ∀ x, (R : ℝ) ≤ ‖x‖ → s x = 0)
    (hVL : ∀ x y, ‖x‖ ≤ (R : ℝ) → ‖y‖ ≤ (R : ℝ) → ‖V x - V y‖ ≤ (Kv : ℝ) * ‖x - y‖)
    (hVB : ∀ x, ‖x‖ ≤ (R : ℝ) → ‖V x‖ ≤ (Bv : ℝ)) :
    LipschitzWith (Bs * Kv + Ks * Bv) (fun x => s x • V x) := by
  apply LipschitzWith.of_dist_le_mul
  intro x y
  simp only [dist_eq_norm]
  have hsd : |s x - s y| ≤ (Ks : ℝ) * ‖x - y‖ := by
    have := hsL.dist_le_mul x y
    rwa [Real.dist_eq, dist_eq_norm] at this
  push_cast
  rcases le_or_gt ‖x‖ (R : ℝ) with hx | hx <;> rcases le_or_gt ‖y‖ (R : ℝ) with hy | hy
  · -- both inside: telescoping split
    have hsplit : s x • V x - s y • V y = s x • (V x - V y) + (s x - s y) • V y := by
      rw [smul_sub, sub_smul]; abel
    rw [hsplit]
    refine le_trans (norm_add_le _ _) ?_
    have h1 : ‖s x • (V x - V y)‖ ≤ (Bs : ℝ) * ((Kv : ℝ) * ‖x - y‖) := by
      rw [norm_smul, Real.norm_eq_abs]
      exact mul_le_mul (hsB x) (hVL x y hx hy) (norm_nonneg _) (by positivity)
    have h2 : ‖(s x - s y) • V y‖ ≤ ((Ks : ℝ) * ‖x - y‖) * (Bv : ℝ) := by
      rw [norm_smul, Real.norm_eq_abs]
      exact mul_le_mul hsd (hVB y hy) (norm_nonneg _) (by positivity)
    calc ‖s x • (V x - V y)‖ + ‖(s x - s y) • V y‖
        ≤ (Bs : ℝ) * ((Kv : ℝ) * ‖x - y‖) + ((Ks : ℝ) * ‖x - y‖) * (Bv : ℝ) := add_le_add h1 h2
      _ = ((Bs : ℝ) * Kv + Ks * Bv) * ‖x - y‖ := by ring
  · -- x inside, y outside: s y = 0
    have hsy : s y = 0 := hvanish y hy.le
    rw [hsy, zero_smul, sub_zero, norm_smul, Real.norm_eq_abs]
    have hsx : |s x| ≤ (Ks : ℝ) * ‖x - y‖ := by simpa [hsy] using hsd
    calc |s x| * ‖V x‖ ≤ ((Ks : ℝ) * ‖x - y‖) * (Bv : ℝ) :=
          mul_le_mul hsx (hVB x hx) (norm_nonneg _) (by positivity)
      _ ≤ ((Bs : ℝ) * Kv + Ks * Bv) * ‖x - y‖ := by
          nlinarith [mul_nonneg (mul_nonneg Bs.coe_nonneg Kv.coe_nonneg) (norm_nonneg (x - y))]
  · -- x outside, y inside: s x = 0
    have hsx : s x = 0 := hvanish x hx.le
    rw [hsx, zero_smul, zero_sub, norm_neg, norm_smul, Real.norm_eq_abs]
    have hsy : |s y| ≤ (Ks : ℝ) * ‖x - y‖ := by simpa [hsx] using hsd
    calc |s y| * ‖V y‖ ≤ ((Ks : ℝ) * ‖x - y‖) * (Bv : ℝ) :=
          mul_le_mul hsy (hVB y hy) (norm_nonneg _) (by positivity)
      _ ≤ ((Bs : ℝ) * Kv + Ks * Bv) * ‖x - y‖ := by
          nlinarith [mul_nonneg (mul_nonneg Bs.coe_nonneg Kv.coe_nonneg) (norm_nonneg (x - y))]
  · -- both outside: s x = s y = 0
    rw [hvanish x hx.le, hvanish y hy.le, zero_smul, zero_smul, sub_zero, norm_zero]
    positivity

theorem normCutoff_lipschitz : LipschitzWith 1 (normCutoff (d := d)) := by
  have hsub : LipschitzWith 1 (fun x : Eucl d => 2 - ‖x‖) := by
    apply LipschitzWith.of_dist_le_mul
    intro x y
    have heq : (2 - ‖x‖) - (2 - ‖y‖) = ‖y‖ - ‖x‖ := by ring
    rw [Real.dist_eq, heq, abs_sub_comm]
    simpa [dist_eq_norm] using abs_norm_sub_norm_le x y
  have hmin : LipschitzWith 1 (fun x : Eucl d => min 1 (2 - ‖x‖)) :=
    hsub.const_min 1
  have hmax : LipschitzWith 1 (fun x : Eucl d => max 0 (min 1 (2 - ‖x‖))) :=
    hmin.const_max 0
  exact hmax

/-!
## The concrete gated field and its `Block`

The paper's cap-transport characteristic (B.5) is `V(x) = (⟪z,x⟫ - cos R)₊ · P_x^⊥ ω`. Multiplied by
the cutoff `χ = normCutoff` it becomes globally Lipschitz and bounded, hence a genuine `Block`. We
build it as `field x = gateFactor x • tangentialProjector x ω` with `gateFactor = normCutoff · reluGate`.
Because the field is `gateFactor • (true projector)` *everywhere* (the cutoff only tames the Lipschitz
estimate, it does not alter the field's algebra), the radial-tangency identity holds by a global
computation, with gate `c(x) = -gateFactor x · ⟪x,ω⟫`.
-/

/-- The ReLU gate `(⟪z,x⟫ - cos R)₊`. For a unit `z` it is `1`-Lipschitz and, on any ball, bounded. -/
noncomputable def reluGate (z : Eucl d) (cosR : ℝ) (x : Eucl d) : ℝ := max 0 (⟪z, x⟫ - cosR)

theorem reluGate_nonneg (z : Eucl d) (cosR : ℝ) (x : Eucl d) : 0 ≤ reluGate z cosR x :=
  le_max_left _ _

/-- On the ball of radius `2`, with unit `z` and `cos R ≥ -1`, the ReLU gate is bounded by `3`. -/
theorem reluGate_le_three {z : Eucl d} (hz : ‖z‖ = 1) {cosR : ℝ} (hcosR : -1 ≤ cosR)
    {x : Eucl d} (hx : ‖x‖ ≤ 2) : reluGate z cosR x ≤ 3 := by
  have hzx : ⟪z, x⟫ ≤ 2 := by
    calc ⟪z, x⟫ ≤ |⟪z, x⟫| := le_abs_self _
      _ ≤ ‖z‖ * ‖x‖ := abs_real_inner_le_norm z x
      _ ≤ 1 * 2 := by rw [hz]; nlinarith [norm_nonneg x]
      _ = 2 := one_mul 2
  unfold reluGate
  apply max_le (by norm_num)
  linarith

/-- The ReLU gate is globally `1`-Lipschitz when `‖z‖ ≤ 1` (Cauchy-Schwarz on the inner factor,
then the `1`-Lipschitz clamp `max 0`). -/
theorem reluGate_lipschitz {z : Eucl d} (hz : ‖z‖ ≤ 1) (cosR : ℝ) :
    LipschitzWith 1 (reluGate z cosR) := by
  have hmax : LipschitzWith 1 (fun t : ℝ => max 0 t) := by
    simpa using (LipschitzWith.id (α := ℝ)).const_max 0
  apply LipschitzWith.of_dist_le_mul
  intro x y
  have h1 : dist (reluGate z cosR x) (reluGate z cosR y) ≤ dist (⟪z, x⟫ - cosR) (⟪z, y⟫ - cosR) := by
    have := hmax.dist_le_mul (⟪z, x⟫ - cosR) (⟪z, y⟫ - cosR)
    simpa [reluGate] using this
  refine h1.trans ?_
  rw [Real.dist_eq, NNReal.coe_one, one_mul, dist_eq_norm]
  have heq : (⟪z, x⟫ - cosR) - (⟪z, y⟫ - cosR) = ⟪z, x - y⟫ := by rw [inner_sub_right]; ring
  rw [heq]
  calc |⟪z, x - y⟫| ≤ ‖z‖ * ‖x - y‖ := abs_real_inner_le_norm z (x - y)
    _ ≤ ‖x - y‖ := by nlinarith [norm_nonneg (x - y)]

/-- The full **gate scalar** `s(x) = χ(‖x‖)·(⟪z,x⟫ - cos R)₊`: the cutoff times the ReLU gate. -/
noncomputable def gateFactor (z : Eucl d) (cosR : ℝ) (x : Eucl d) : ℝ :=
  normCutoff x * reluGate z cosR x

/-- `gateFactor` vanishes outside the ball of radius `2` (the cutoff kills it). -/
theorem gateFactor_eq_zero {z : Eucl d} {cosR : ℝ} {x : Eucl d} (hx : 2 ≤ ‖x‖) :
    gateFactor z cosR x = 0 := by
  rw [gateFactor, normCutoff_eq_zero hx, zero_mul]

/-- Global bound: `|gateFactor x| ≤ 3` (bounded by the ReLU gate on the support, zero off it). -/
theorem abs_gateFactor_le {z : Eucl d} (hz : ‖z‖ = 1) {cosR : ℝ} (hcosR : -1 ≤ cosR) (x : Eucl d) :
    |gateFactor z cosR x| ≤ 3 := by
  rcases le_or_gt 2 ‖x‖ with hx | hx
  · rw [gateFactor_eq_zero hx]; norm_num
  · rw [gateFactor, abs_mul, abs_of_nonneg (normCutoff_nonneg x),
      abs_of_nonneg (reluGate_nonneg z cosR x)]
    calc normCutoff x * reluGate z cosR x ≤ 1 * 3 :=
          mul_le_mul (normCutoff_le_one x) (reluGate_le_three hz hcosR hx.le)
            (reluGate_nonneg z cosR x) zero_le_one
      _ = 3 := one_mul 3

/-- `gateFactor` is globally `4`-Lipschitz: apply the vanishing-gluing lemma with the globally
bounded `1`-Lipschitz cutoff and the on-ball-bounded ReLU gate (`Bs·Kv + Ks·Bv = 1·1 + 1·3`). -/
theorem gateFactor_lipschitz {z : Eucl d} (hz : ‖z‖ = 1) {cosR : ℝ} (hcosR : -1 ≤ cosR) :
    LipschitzWith 4 (gateFactor z cosR) := by
  have h := lipschitzWith_smul_of_vanishing (F := ℝ) (Ks := 1) (Bs := 1) (Kv := 1) (Bv := 3)
    (R := 2) (s := normCutoff) (V := reluGate z cosR)
    normCutoff_lipschitz (fun x => abs_normCutoff_le_one x)
    (fun x hx => normCutoff_eq_zero hx)
    (fun x y _ _ => by
      have h := (reluGate_lipschitz hz.le cosR).dist_le_mul x y
      simpa [Real.dist_eq, dist_eq_norm, Real.norm_eq_abs, NNReal.coe_one, one_mul] using h)
    (fun x hx => by
      rw [Real.norm_eq_abs, abs_of_nonneg (reluGate_nonneg z cosR x)]
      exact reluGate_le_three hz hcosR hx)
  have hconst : (1 : NNReal) * 1 + 1 * 3 = 4 := by norm_num
  rw [hconst] at h
  simp only [smul_eq_mul] at h
  exact h

/-- On the ball of radius `2`, with unit `ω`, the tangential projector `ω - ⟪x,ω⟫x` is bounded by
`5` (`‖ω‖ + |⟪x,ω⟫|‖x‖ ≤ 1 + ‖x‖²`). -/
theorem tangentialProjector_norm_le {ω : Eucl d} (hω : ‖ω‖ = 1) {x : Eucl d} (hx : ‖x‖ ≤ 2) :
    ‖tangentialProjector x ω‖ ≤ 5 := by
  have hcs : |⟪x, ω⟫| ≤ ‖x‖ * ‖ω‖ := abs_real_inner_le_norm x ω
  have h1 : ‖tangentialProjector x ω‖ ≤ ‖ω‖ + |⟪x, ω⟫| * ‖x‖ := by
    rw [tangentialProjector]
    calc ‖ω - ⟪x, ω⟫ • x‖ ≤ ‖ω‖ + ‖⟪x, ω⟫ • x‖ := norm_sub_le _ _
      _ = ‖ω‖ + |⟪x, ω⟫| * ‖x‖ := by rw [norm_smul, Real.norm_eq_abs]
  rw [hω] at hcs h1
  nlinarith [h1, mul_le_mul_of_nonneg_right hcs (norm_nonneg x),
    mul_le_mul hx hx (norm_nonneg x) (by norm_num : (0 : ℝ) ≤ 2)]

/-- On the ball of radius `2`, with unit `ω`, the tangential projector is `4`-Lipschitz in `x`. The
difference `⟪y,ω⟫y - ⟪x,ω⟫x` splits as `⟪y,ω⟫(y-x) + (⟪y,ω⟫-⟪x,ω⟫)x`, each factor Cauchy-Schwarz
bounded by `2` on the ball. -/
theorem tangentialProjector_lipschitz_onBall {ω : Eucl d} (hω : ‖ω‖ = 1)
    {x y : Eucl d} (hx : ‖x‖ ≤ 2) (hy : ‖y‖ ≤ 2) :
    ‖tangentialProjector x ω - tangentialProjector y ω‖ ≤ 4 * ‖x - y‖ := by
  have hexp : tangentialProjector x ω - tangentialProjector y ω
      = ⟪y, ω⟫ • (y - x) + (⟪y, ω⟫ - ⟪x, ω⟫) • x := by
    simp only [tangentialProjector]; module
  have hcy : |⟪y, ω⟫| ≤ 2 := by
    calc |⟪y, ω⟫| ≤ ‖y‖ * ‖ω‖ := abs_real_inner_le_norm y ω
      _ ≤ 2 := by rw [hω]; nlinarith [hy, norm_nonneg y]
  have hcd : |⟪y, ω⟫ - ⟪x, ω⟫| ≤ ‖x - y‖ := by
    have heq : ⟪y, ω⟫ - ⟪x, ω⟫ = ⟪y - x, ω⟫ := by rw [inner_sub_left]
    rw [heq]
    calc |⟪y - x, ω⟫| ≤ ‖y - x‖ * ‖ω‖ := abs_real_inner_le_norm _ _
      _ = ‖x - y‖ := by rw [hω, mul_one, norm_sub_rev]
  rw [hexp]
  calc ‖⟪y, ω⟫ • (y - x) + (⟪y, ω⟫ - ⟪x, ω⟫) • x‖
      ≤ ‖⟪y, ω⟫ • (y - x)‖ + ‖(⟪y, ω⟫ - ⟪x, ω⟫) • x‖ := norm_add_le _ _
    _ = |⟪y, ω⟫| * ‖y - x‖ + |⟪y, ω⟫ - ⟪x, ω⟫| * ‖x‖ := by
        rw [norm_smul, norm_smul, Real.norm_eq_abs, Real.norm_eq_abs]
    _ ≤ 2 * ‖x - y‖ + ‖x - y‖ * 2 := by
        rw [norm_sub_rev y x]
        exact add_le_add (mul_le_mul_of_nonneg_right hcy (norm_nonneg _))
          (mul_le_mul hcd hx (norm_nonneg x) (norm_nonneg _))
    _ = 4 * ‖x - y‖ := by ring

/-- The **gated cutoff field** `V(x) = χ(‖x‖)·(⟪z,x⟫ - cos R)₊ · P_x^⊥ ω` of Appendix B.5, written as
`gateFactor · tangentialProjector`. -/
noncomputable def gatedField (z ω : Eucl d) (cosR : ℝ) (x : Eucl d) : Eucl d :=
  gateFactor z cosR x • tangentialProjector x ω

/-- The gated field is globally `32`-Lipschitz: the vanishing-gluing lemma with the compactly
supported `gateFactor` (`Ks=4`, `Bs=3`, vanishing outside the ball of radius `2`) and the projector,
bounded (`5`) and Lipschitz (`4`) on that ball (`Bs·Kv + Ks·Bv = 3·4 + 4·5 = 32`). -/
theorem gatedField_lipschitz {z ω : Eucl d} (hz : ‖z‖ = 1) (hω : ‖ω‖ = 1) {cosR : ℝ}
    (hcosR : -1 ≤ cosR) : LipschitzWith 32 (gatedField z ω cosR) := by
  have h := lipschitzWith_smul_of_vanishing (F := Eucl d) (Ks := 4) (Bs := 3) (Kv := 4) (Bv := 5)
    (R := 2) (s := gateFactor z cosR) (V := fun x => tangentialProjector x ω)
    (gateFactor_lipschitz hz hcosR) (fun x => abs_gateFactor_le hz hcosR x)
    (fun x hx => gateFactor_eq_zero hx)
    (fun x y hx hy => by
      have := tangentialProjector_lipschitz_onBall hω hx hy; push_cast; linarith)
    (fun x hx => by have := tangentialProjector_norm_le hω hx; push_cast; linarith)
  have hconst : (3 : NNReal) * 4 + 4 * 5 = 32 := by norm_num
  rw [hconst] at h
  exact h

/-- The gated field is globally bounded by `15` (`|gateFactor| ≤ 3` times the projector bound `5` on
the support, zero off it). -/
theorem gatedField_norm_le {z ω : Eucl d} (hz : ‖z‖ = 1) (hω : ‖ω‖ = 1) {cosR : ℝ}
    (hcosR : -1 ≤ cosR) (x : Eucl d) : ‖gatedField z ω cosR x‖ ≤ 15 := by
  rw [gatedField, norm_smul, Real.norm_eq_abs]
  rcases le_or_gt 2 ‖x‖ with hx | hx
  · rw [gateFactor_eq_zero hx, abs_zero, zero_mul]; norm_num
  · calc |gateFactor z cosR x| * ‖tangentialProjector x ω‖ ≤ 3 * 5 :=
          mul_le_mul (abs_gateFactor_le hz hcosR x) (tangentialProjector_norm_le hω hx.le)
            (norm_nonneg _) (by norm_num)
      _ = 15 := by norm_num

/-- The radial **gate** `c(x) = -gateFactor x · ⟪x,ω⟫`. -/
noncomputable def gatedGate (z ω : Eucl d) (cosR : ℝ) (x : Eucl d) : ℝ :=
  -(gateFactor z cosR x * ⟪x, ω⟫)

/-- The **radial-tangency identity**: `⟪x, V(x)⟫ = c(x)·(‖x‖² - 1)`, holding for all `x` by a global
computation (`⟪x, P_x^⊥ ω⟫ = ⟪x,ω⟫(1 - ‖x‖²)`). This makes the flow preserve the unit sphere. -/
theorem gatedField_radial (z ω : Eucl d) (cosR : ℝ) (x : Eucl d) :
    ⟪x, gatedField z ω cosR x⟫ = gatedGate z ω cosR x * (‖x‖ ^ 2 - 1) := by
  rw [gatedField, gatedGate, real_inner_smul_right, tangentialProjector, inner_sub_right,
    real_inner_smul_right, real_inner_self_eq_norm_sq]
  ring

/-- Uniform bound on twice the gate: `|2·c(x)| ≤ 12` (`|gateFactor| ≤ 3` and `|⟪x,ω⟫| ≤ 2` on the
support, zero off it). -/
theorem abs_two_gatedGate_le {z ω : Eucl d} (hz : ‖z‖ = 1) (hω : ‖ω‖ = 1) {cosR : ℝ}
    (hcosR : -1 ≤ cosR) (x : Eucl d) : |2 * gatedGate z ω cosR x| ≤ 12 := by
  rcases le_or_gt 2 ‖x‖ with hx | hx
  · rw [gatedGate, gateFactor_eq_zero hx]; simp
  · have hi : |⟪x, ω⟫| ≤ 2 := by
      calc |⟪x, ω⟫| ≤ ‖x‖ * ‖ω‖ := abs_real_inner_le_norm x ω
        _ ≤ 2 := by rw [hω]; nlinarith [hx.le, norm_nonneg x]
    have hgf := abs_gateFactor_le hz hcosR x
    have hrw : |2 * gatedGate z ω cosR x| = 2 * (|gateFactor z cosR x| * |⟪x, ω⟫|) := by
      rw [gatedGate, mul_neg, abs_neg, abs_mul, abs_mul]; norm_num
    rw [hrw]
    nlinarith [mul_le_mul hgf hi (abs_nonneg (⟪x, ω⟫)) (by norm_num : (0 : ℝ) ≤ 3)]

/-- **The gated cutoff `Block`.** For unit `z, ω` and threshold `cos R ≥ -1`, the ReLU-gated field of
Appendix B.5, tamed by the cutoff, is a genuine well-posed `Block`: globally `32`-Lipschitz, bounded
by `15`, radially tangent with gate `c(x) = -gateFactor x·⟪x,ω⟫`, over any nonnegative duration `T`. -/
noncomputable def gatedBlock {z ω : Eucl d} (hz : ‖z‖ = 1) (hω : ‖ω‖ = 1) {cosR : ℝ}
    (hcosR : -1 ≤ cosR) {T : ℝ} (hT : 0 ≤ T) : Block d where
  field := gatedField z ω cosR
  lipConst := 32
  lipschitz := gatedField_lipschitz hz hω hcosR
  bound := 15
  field_le := fun x => by have := gatedField_norm_le hz hω hcosR x; push_cast; linarith
  gate := gatedGate z ω cosR
  gateBound := 12
  gate_le := abs_two_gatedGate_le hz hω hcosR
  radial := gatedField_radial z ω cosR
  dur := T
  dur_nonneg := hT

end MeasureToMeasure
